- id: commitlint
  name: commitlint
  description: run commitlint
  entry: commitlint --edit
  language: node
  stages:
    - commit-msg
  additional_dependencies:
    - "@commitlint/cli@16.2.1"
    - "@commitlint/config-conventional@16.2.1"
